services:
  proxy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

  app:
    build: .
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      - CONNECTION_STRING=postgres://postgres:container_password@postgres/invoicer

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: container_password
      POSTGRES_DB: invoicer
    volumes:
      - ./postgres:/var/lib/postgresql/data
